name: Push Daily Class Schedule

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * *'  # 每天北京时间早上7点执行（UTC+0 23点）

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v3

      - name: 设置 Python 环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: 查看当前目录
        run: pwd && ls -al

      - name: 安装依赖
        run: pip install -r requirements.txt

      - name: 执行推送脚本
        working-directory: .
        env:
          PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
          BARK_TOKEN: ${{ secrets.BARK_TOKEN }}
          BARK_DEVICE_KEY: ${{ secrets.BARK_DEVICE_KEY }}
        run: python push.py
